config/routes.rb
Rainforest::Application.routes.draw do

  get "reviews/show"
  get "reviews/new"
  get "reviews/edit"
  resources :products do
    resources :reviews, :except => [:index]
  end

  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  has_many :users, :through => :reviews


  validates :description, :name, :presence => true
  validates :price_in_cents, :numericality => {:only_integer => true}

  def format_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

  validates :comment, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  has_many :products, :through => :reviews

  validates :email, presence: true
  validates :email, format: { with: /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,11}/i, message: "must be valid (eg. name@domain.com)"}
  validates :password, length: { in: 6..20 }
  validates :username, presence: true

  has_secure_password


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in first!"
      redirect_to new_session_path
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :ensure_logged_in, only: [:new, :create, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    if current_user
      @review = @product.reviews.new
    end
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end


  private
  def product_params
    params.require(:product).permit(:name,:description,:price_in_cents)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :load_product
  before_filter :ensure_logged_in, :only => [:edit, :create, :update, :show, :destroy]

  def show
    @review = Review.find(params[:id])
  end

  def new
  end

  def create
    @review = @product.reviews.new(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to product_path(@product), notice: "Review published!"
    else
      render template: "products/show"
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@product), notice: "Review deleted."
  end


  private

  def review_params
    params.require(:review).permit(:comment, :product_id)
  end

  def load_product
    @product = Product.find(params[:product_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by("email = ?", params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_path, notice: "Logged in!"
    else
      flash.now[:alert] = "Invalid login details"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_path, notice: "Logged out."
  end


  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to products_path, :notice => "Signed up!"
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest</title>
  <link href='http://fonts.googleapis.com/css?family=Sniglet|Ruluko' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to (image_tag "rainforest_logo.png", class: "logo"), products_path %>

<% if current_user %>
<div class="add_product_button">
  <div class="add_product_link">
    <%= link_to "+", new_product_path %>
  </div>
</div>
<% end %>

<div class="user_panel">
  <ul>
    <% if current_user %>
      <li>Logged in as <span class="current_user_email"><%= current_user.username %></span>.</li>
      <li><%= link_to "Log out", session_path("current"), method: :delete %></li>
    <% else %>
      <li><%= link_to "Log In", new_session_path %></li>
      <li><%= link_to "Register Account", new_user_path %></li>
    <% end %>
  </ul>
</div>

<% if flash[:alert] %>
  <div class="flash_alert"><strong>Error:</strong> <%= flash[:alert] %></div>
<% end %>
<% if flash[:notice] %>
  <div class="flash_notice"><%= flash[:notice] %></div>
<% end %>

<%= yield %>

</body>
</html>

app/views/products/_add_review.html.erb
<% if current_user %>
  <h3 style="margin-top: 25px;">Add a New Review</h3>
  <%= form_for([@product, @review]) do |f| %>
    <% if @review.errors.any? %>
      <h4>Found <%= pluralize(@review.errors.count, "error") %>.</h4>
      <ul>
        <% @review.errors.full_messages.each do |err| %>
          <li><%= err %></li>
        <% end %>
    <% end %>
    <%= f.label :comment %>
    <%= f.text_area :comment %>
    <br><br>
    <%= f.submit "Publish Review" %>
  <% end %>

<% end %>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h4>Oh no! We found <%= pluralize(@product.errors.count, "error")%>!</h4>

      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label "Product Name:" %>
  <%= f.text_field :name %>
  <br>
  <%= f.label "Product Description:" %>
  <%= f.text_area :description %>
  <br>
  <%= f.label "Price (in cents):" %>
  <%= f.text_field :price_in_cents %>
  <br><br>
  <%= f.submit %>

<% end %>

app/views/products/_show_reviews.html.erb
<h2>Reviews for <%= @product.name %></h2>



<% @product.reviews.each do |review| %>
  <% next if review.user.nil? || review.errors.any? %>
  <div class="review">
    <p><%= review.comment %></p>
    <p class="review_author">By <%= review.user.email %> on <%= review.created_at %></p>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="new_product_container">
  <h1>Edit Product</h1>
  <%= render 'form' %>
  <br>
  <%= link_to "< Back", products_path %>
</div>

app/views/products/index.html.erb
<div class="index_product_div">
  <% @products.each do |p| %>
    <div class="index_product_container">
      <h3><%= link_to p.name, product_path(p.id) %></h3>
      <p class="index_product_description"><%= p.description %></p>
      <p class="index_product_price"><sup>$</sup><%= p.format_price %></p>
    </div>


  <% end %>
</div>

app/views/products/new.html.erb
<div class="new_product_container">
  <h1>Add New Product</h1>
  <%= render 'form' %>
  <br>
  <%= link_to "< Back", products_path %>
</div>

app/views/products/show.html.erb
<div class="show_product_wrapper">
  <h1><%= @product.name %></h1>
  <p class="show_product_description"><%= @product.description %></p>
  <p class="show_product_price">Only <sup>$</sup><%= @product.format_price %></p>
  <p><%= link_to "Edit", edit_product_path(@product.id) %> 
      | 
     <%= link_to "Delete", product_path(@product.id), method: :delete, id: "show_product_edit_link" %>
</div>

<div class="reviews_wrapper">
  <%= render 'products/show_reviews' %>
  <%= render 'products/add_review' %>
</div>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/new.html.erb
<h2>Register a New Account</h2>

<div class="register_account_div">

  
  <%= form_for @user do |f| %>
    <div class="register_errors">
      <% if @user.errors.any? %>
        <h3>Found <%= pluralize(@user.errors.count, "Error") %></h3>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  <%= f.label "Username:" %>
  <%= f.text_field :username %>
  <br>
  <%= f.label "Email:" %>
  <%= f.text_field :email %>
  <br>
  <%= f.label "Password:" %>
  <%= f.password_field :password %>
  <br>
  <%= f.label "Confirm Password:" %>
  <%= f.password_field :password_confirmation %>
  <br><br>
  <%= f.submit %>

  <% end %>

</div>